### ISSUE TITLE
Question: default group and weight.

### ISSUE THREAD

**Issue by 5igm** [KaiKikuchi/SimplePermissions#2]
1. How can I set a group as a default group? 
2. What is weight?

**Comment by KaiKikuchi** [comment]
You cannot set a group as default: there is a built-in "default" group. You can add a parent to the default group, so it'll become a default group (but you'll still have a "default" group). Still, to avoid confusion, I suggest you to use the "default" group. Just use `/pgroup default add [permission]`

The weight is the "priority" when a player is in multiple groups. e.g.: user "UserA" is in groups "GroupA" and "GroupB".
GroupA has "minecraft.command.tell" permission, and GroupB has "-minecraft.command.tell" (this will deny the permission). If the GroupA weight is higher than GroupB weight, then UserA will have the tell permission, otherwise they will not have the permission.
